### ISSUE TITLE
the patch embbeder implementations are different from the original paper

### ISSUE THREAD

**Issue by mikegreen7892003** [lucidrains/MEGABYTE-pytorch#11]
Thank you so much for taking the time to share your code with me! I appreciate your generosity in helping me better understand the paper.

I noticed that your code has a slightly unique approach to implementing the Patch Embedder in comparison to the original.

The original paper implementation of  Patch Embedder uses separate global and local byte embeddings, followed by concatenation in the global model. Your implementation, however, involves using fixed bytes embedding and linear transformations between different transformers to construct the patch embedding.

# the paper
![image](https://github.com/lucidrains/MEGABYTE-pytorch/assets/1708334/d6038834-c33b-4f2b-9210-7adeecabb5a4)

# your code
```Python
self.patch_embedders = nn.ModuleList([nn.Sequential(
    Rearrange('... r d -> ... (r d)'),
    nn.LayerNorm(seq_len * dim_in),
    nn.Linear(seq_len * dim_in, dim_out),  # linear transformations here
    nn.LayerNorm(dim_out)
) for dim_in, dim_out, seq_len in zip(dim[1:], dim[:-1], max_seq_len[1:])])
```

**Comment by lucidrains** [comment]
@mikegreen7892003 i don't think this is a big deal, but i can take a look at it mid June once i am back online

**Comment by darkman111a** [comment]
I'm interested in this as well. Appreciate you OG. Stay blessed!

**Comment by lucidrains** [comment]
@mikegreen7892003 do you want to see if 0.2.0 brings the code closer to what your understand of the paper?

**Comment by darkman111a** [comment]
@lucidrains you're really the chosen one. Looks good to me. Appreciate all your hard work.
