### ISSUE TITLE
Why your Attention impl use kv dimention dim_head instead of inner_dim?

### ISSUE THREAD

**Issue by Earthson** [lucidrains/MEGABYTE-pytorch#13]
```python
self.to_kv = nn.Linear(dim, dim_head * 2, bias = False) 
# expected
self.to_kv = nn.Linear(dim, inner_dim * 2, bias = False)
```

Is this a trick? or bug?

**Comment by lucidrains** [comment]
@Earthson i was using the one key-value head from [this paper](https://arxiv.org/abs/1911.02150), but most models these days are moving towards grouped query attention (> 1 kv head), so let's just go with the full set of heads for now
