### ISSUE TITLE
Why does it expect tokens?

### ISSUE THREAD

**Issue by tonydavis629** [lucidrains/MEGABYTE-pytorch#16]
The input to this implementation is a token (0-16000). Isn't the whole point of the original paper that the input is a byte (0-255)? Am I missing something about the patch embedding?

**Comment by lucidrains** [comment]
that's just the readme example

you can execute a working demo for character level enwik8 here with 256 tokens https://github.com/lucidrains/MEGABYTE-pytorch/blob/main/train.py#L38
