### ISSUE TITLE
What are the implications of this model?

### ISSUE THREAD

**Issue by kyegomez** [lucidrains/MEGABYTE-pytorch#2]
Is this model feasible and ready to start being implemented on a massive scale? Do you think it's useful? What do you think in general about Megabyte?

**Comment by lucidrains** [comment]
the paper demonstrates that one can learn a tokenizer end-to-end, starting from character representations, without having to worry about BPE, sentencepiece etc.

if one wants to extend the vision further, the end result may be a generalized architecture for learning hierarchical (multiscale) representations on any modality.

**Comment by lucidrains** [comment]
@kyegomez more research needed, but i've seen multiple papers attempt this already with good results, so i'm personally bullish on the direction

**Comment by kyegomez** [comment]
Is it easily integratabtle with vanilla transformers or does the entire transformer architecture have to change to accomodate MEGABYTE?

**Comment by lucidrains** [comment]
@kyegomez it won't work with a few minor modifications to existing transformer libraries, if that is what you mean

**Comment by lucidrains** [comment]
@kyegomez but still quite simple. the repository is < 400 loc
