### ISSUE TITLE
Allow usage as single-stage transformer

### ISSUE THREAD

**Issue by eegli** [lucidrains/MEGABYTE-pytorch#20]
It's me again, hi!

Maybe you could refactor the line `coarsest_dim, *_, fine_dim = dim` to simply `fine_dim = dim[-1]`.

Since `coarsest_dim` is unused, it has the same effect with the added benefit that the entire package can be used to creating an ordinary (single-stage) transformer. Allowing that would be very useful for ablating hierarchies.

Sorry that all my requests and issues have been coming in one after another instead of batched. Thanks a lot for your amazing work!

**Comment by lucidrains** [comment]
sounds good, done
