### ISSUE TITLE
Missing package in setup

### ISSUE THREAD

**Issue by eegli** [lucidrains/MEGABYTE-pytorch#21]
`packaging` is missing in `setup.py` and can break downstream installations. Would be nice to add it.

**Comment by lucidrains** [comment]
@eegli done!

**Comment by lucidrains** [comment]
@eegli take a look at [byte latent transformer](https://ai.meta.com/research/publications/byte-latent-transformer-patches-scale-better-than-tokens/)

**Comment by eegli** [comment]
Thanks a lot for the quick fix! I've seen it and I like it. Patch-based modeling is the new meta!
