### ISSUE TITLE
Some question about the MEGABYTE

### ISSUE THREAD

**Issue by relic-yuexi** [lucidrains/MEGABYTE-pytorch#4]
First of all, thank you for the author's contribution. Is this MEGABYTE only suitable for ASCII encoding? If you use Unicode, will it go wrong, easy to explode memory, then how to achieve character-level segmentation?

**Comment by relic-yuexi** [comment]
For character-level model, how to set the termination mark, the sequence generated behind are meaningless spaces, but afraid that some sentences have spaces.

like "<EOF>" will be sepreate "<" "E" "O" "F" ">"

**Comment by Law-Lawliet** [comment]
@relic-yuexi small question since looks like you were able to make the code work. Can you show me in some way how to make this work ? Sorry I'm new to AI stuff

**Comment by relic-yuexi** [comment]
> 

Me too. I just want to makea small GPT-like model in chinese. By my experiment, it looks like it has a faster speed than the tradtional Transfomer. And it can use none complex tokenizer, i just use the func ord() to tokenizer the unicode.

Just input some text as the dataset, then modify the train.py as you like.

**Comment by relic-yuexi** [comment]
When i used the ord(" ") as a pad_id, it will lead to nan loss and hard training and error code.
