### ISSUE TITLE
No available kernel error

### ISSUE THREAD

**Issue by missflash** [lucidrains/MEGABYTE-pytorch#6]
Thank you for your code.

I tried to train MEGABYTE using default settings, but I faced the following error.
How can I fix it?

```
.../MEGABYTE_pytorch/attend.py", line 111, in flash_attn
    out = F.scaled_dot_product_attention(
RuntimeError: No available kernel.  Aborting execution.
```

**Comment by lucidrains** [comment]
https://github.com/lucidrains/MEGABYTE-pytorch/blob/main/train.py#L43 you will have to set this to `False`
