### ISSUE TITLE
some implementations are different from the original paper

### ISSUE THREAD

**Issue by ZihaoH** [lucidrains/MEGABYTE-pytorch#7]
Hi, thanks to your advance code helping me to understand original paper!

Given only global_transformer and local_transformer, I found that your codes are different at some points：

let's set D_G=768, D_L=256, P=4, seq=40,batch_size=1,  
1. then h^global_out shape is (1, 1+10, 768) in your code, but it should be (1, 1+10, 4 * 768) in paper (1+10 means first pad token + following patch tokens). There are two token_emb func in original paper for h^global_in and h^local_in, your code only has a token_emb for h^local_in.
2. the proj between global and local transformer projects dim 768 to 256, your code is doing this:
- h^global_out.shape=(1, 11, 768), choose top10 token, then h^global_out.shape=(1, 10, 768)
- h^global_out = proj(h^global_out), then h^global_out.shape=(1, 10, 256)
- h^local_in.shape=(10, 4, 256), concat with h^global_out, the final h^local_in has a shape of (10, 5, 256). at the end, drop the first token

    in the original paper, it does

- h^global_out.shape=(1, 11, 4 * 768), choose top10 token, then h^global_out.shape=(1, 10, 4 * 768)
- h^global_out = proj(h^global_out), then h^global_out.shape=(1, 10, 4 * 256)
- h^local_in = concat([pad, top3 token in h^local_in]) + h^global_out.reshape(10, 4, 256), which will drop last token in h_local_in. 
<img width="864" alt="image" src="https://github.com/lucidrains/MEGABYTE-pytorch/assets/60248699/9806bbfc-35e2-40f1-85c3-c1939ae6abc5">

Please take a look and see if I misunderstand something. Looking forward to your apply!

**Comment by lucidrains** [comment]
@ZihaoH 

yea you are correct, i didn't do the implementation to the exact detail

number one, this will be negligible difference

i just tried out their #2, but didn't see better results than the way i did it, and code ends up being more complicated. you are welcome to [give it a run](https://github.com/lucidrains/MEGABYTE-pytorch/commit/ede6166ddb1e8ea4f7df2c9caa3ce789c893420e) (or if you can spot a bug, let me know)

**Comment by lucidrains** [comment]
@ZihaoH nevermind i found the bug and it converges ok, just released in 0.1.0

their design for number 2 may have slightly better gradients
